# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
    branches:
      - "**"
      - "!main"
  pull_request:
    branches:
      - main
    types: [opened, synchronize, closed]

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
  build:
    if: (!(github.event.action == 'closed' && github.event.pull_request.merged != true))
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    #For AppCore
    - name: Install MAUI Workload
      run: dotnet workload install maui --ignore-failed-sources
        
    - name: Restore dependencies for MAUI 
      run: dotnet restore 
      working-directory: MoneyManager/AppCore/AppCore.csproj
      
    - name: Build
      run: dotnet build 
      working-directory: MoneyManager/AppCore/AppCore.csproj
      
#     - name: Build MAUI Windows
#       run: dotnet publish MoneyManager/AppCore/AppCore.csproj -c Release -f net7.0-android --no-restore
      
#     - name: Test
#       run: dotnet test --no-build --verbosity normal
      
    #For ServerSide
    - name: Restore dependencies for ASP.NET core
      run: dotnet restore 
      working-directory: MoneyManager/AppServer/AppServer.csproj
      
    - name: Setup .NET Core SDK
    - run: dotnet build 
    - working-directory: MoneyManager/AppServer/AppServer.csproj
    
